### ISSUE TITLE
Save the adversarial example image and get the difference image

### ISSUE THREAD

**Issue by newwhitecheng** [e-lab/torch-toolbox#14]
Hello, 
I'm recently playing your adversarial example code. Everything works well, but I'm wondering how to save the adversarial example and how to get the difference image. As shown in the following one. 
I'm very new to torch, any advice will help.

**Comment by jhjin** [comment]
Now `qlua example.lua` should do that job for you.

**Comment by newwhitecheng** [comment]
Sorry for asking again, I use the code you update, but it still can not save the image correctly.
I add the following code to save image. 
image.save('imag_adv.png',img_adv)
I get a image which is very different from the original image 
The first one is the original image. The second image is the one with adversarial. I don't know how to get a adversarial image save correctly. Do you have any idea? thank you!! 
![car](https://cloud.githubusercontent.com/assets/10292972/19008135/261b3c40-8737-11e6-82c4-06d3ff9e7239.jpg)
![imag_adv](https://cloud.githubusercontent.com/assets/10292972/19008139/2e081090-8737-11e6-8bb5-0a9ba5b05e13.png)

**Comment by jhjin** [comment]
You need to denormalize the image before saving. Please see https://github.com/e-lab/torch-toolbox/commit/b9a90424984b142614003afcfaaa8efcf0c8b5b6 .
