### ISSUE TITLE
Video decoder installation issue on Ubuntu 12.04

### ISSUE THREAD

**Issue by navneet1083** [e-lab/torch-toolbox#17]
Getting issues after compilation with and without **NEWFFMPEG=1**

_./libvideo_decoder.so: undefined symbol: THByteTensor_data_

**Comment by mvitez** [comment]
Try to add -lTH -lluajit -lluaT to LDFLAGS in the Makefile. Put it everywhere, now it's only present for Macs.

**Comment by navneet1083** [comment]
thanks, it did work !!
