### ISSUE TITLE
Fail to install Video-decoder on TX1

### ISSUE THREAD

**Issue by deepcode123** [e-lab/torch-toolbox#18]
Hi, 
I have an error when make Video-decoder in tx1.
This is the error:

gcc: error: unrecognized command line option ‘-mfpu=neon’
Makefile:51: recipe for target 'video_decoder.o' failed
make: *** [video_decoder.o] Error 1

Can this install on aarch64?
Thanks!

**Comment by mvitez** [comment]
We have never tried aarch64, but TX1 is not aarch64, it's arm (32 bit), besides having a 64 bit CPU. We compiled it there successfully, so I don't what happened, maybe you are using another version of the OS that we were using. Try to remove -mfpu=neon from the Makefile or try with other mfpu options (see gcc manual).

**Comment by deepcode123** [comment]
hi, @mvitez 
Can I ask which OS you install in tx1?
I installed jetpack 2.3 (ubuntu 16.04) in it, maybe this is the reason.
Thanks!

**Comment by mvitez** [comment]
I don't have the TX1 physically here and I was not the person that installed the OS there, so I will come to you back later or the right person will answer you.

**Comment by Atcold** [comment]
Hi @deepcode123.
Yes, with the latest JetPack (2.3), you get a 64 bit OS and CUDA 8.
I've just updated our board and running some experiments since last week.
I'll let you know when we figure out what's going on.
I believe this issue https://github.com/torch/torch7/issues/766 might be related.

**Comment by Atcold** [comment]
@deepcode123, we've just patch it up.
Please, give it a try and let us know if all is good now.

**Comment by deepcode123** [comment]
Hi, @Atcold 
Thank you so much!! Everything works well.
