### ISSUE TITLE
Length of video using `libvideo-decoder`

### ISSUE THREAD

**Issue by codeAC29** [e-lab/torch-toolbox#20]
What can be a possible reason to get `nil` value for length of a video after calling `libvideo-decoder` like [this](https://github.com/e-lab/torch-toolbox/blob/master/Video-decoder/test-frame.lua#L18)?

**Comment by jhjin** [comment]
Some of videos do not have their length in the header. I guess also videos in streaming format can have no length in the header.

**Comment by mvitez** [comment]
Video-decoder did not return the total number of frames, because this information was not present. It can be calculated, though, if the video length and fps are present, which is true in your case. I have committed a new version with this fix.
