### ISSUE TITLE
Not able to run video with .MXF extension

### ISSUE THREAD

**Issue by codeAC29** [e-lab/torch-toolbox#21]
I tried to load video with .MXF extension using [test-frame](https://github.com/e-lab/torch-toolbox/blob/master/Video-decoder/test-frame.lua) but it stops/pauses after few frames. In the beginning I get the following warning message too:
```
[mxf @ 0x7f9d9c022720] material track 2: no corresponding source track found
Video statistics: 720x960 (unknown frames)
```

**Comment by mvitez** [comment]
Does ffmpeg open your video? If not, there is little we can do. If yes, can you put the video somewhere for me to check?

**Comment by mvitez** [comment]
GPU0 is a good place where to put.

**Comment by codeAC29** [comment]
ffmpeg is able to open my video. I have put it in GPU0: `/media/HDD1/Datasets`

**Comment by mvitez** [comment]
This file plays correctly to me with your test-frame. Of course, it stops at the 10th frame, because it's written so in the code.

**Comment by mvitez** [comment]
Video-decoder did not return the total number of frames, because this information was not present. It can be calculated, though, if the video length and fps are present, which is true in your case. I have committed a new version with this fix.
