### ISSUE TITLE
Do I need re-initialization after cudnn.covert

### ISSUE THREAD

**Issue by byronwwang** [e-lab/torch-toolbox#22]
I have a question here. We I build a network, I use the methods in Weight-init.lua to initialize the weights of my network which are all 'nn' layers. But, sometimes I need use covert the net to cudnn version, Do I need re-initialization after  cudnn.covert(model, cudnn)? Any easy way?

**Comment by jhjin** [comment]
I do not think reinitialization is needed after the conversion.
`cudnn.convert` swaps metatables therefore should not affect the actual
parameters.

**Comment by byronwwang** [comment]
@jhjin Thanks for your reply. It seems true.
