### ISSUE TITLE
Is cudnn.SpatialConvolution working for weight initialization?

### ISSUE THREAD

**Issue by dlmacedo** [e-lab/torch-toolbox#6]
Dear Friend,

I am interested in using the weight initialization lua script.

But in [https://github.com/NVIDIA/DIGITS/tree/master/examples/weight-init]() is said that cudnn.SpatialConvolution is not working. Is this true?

> NOTE: at the time of writing, the torch-toolbox project does not handle all layers (most notably cudnn.SpatialConvolution) so you might need to tailor the script to your specific needs.

Thanks,

David

**Comment by jhjin** [comment]
@dlmacedo Thanks for your interest. Now the module is supported via the commit https://github.com/e-lab/torch-toolbox/commit/b749556653916ec5286c99e33f80b2c45dbf6c0b Please let me know if it works properly.
