### ISSUE TITLE
torch package installs

### ISSUE THREAD

**Issue by culurciello** [e-lab/torch-toolbox#7]
we now use local installation of Torch7:

remove old with:
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash
from:
https://github.com/torch/ezinstall

then install as: 
http://torch.ch/docs/getting-started.html#_

maybe the packages should go to:
~/torch/install/share/lua/5.1/

**Comment by mvitez** [comment]
Yes, the Makefile was wrong, as it looked for the libraries in the right place, but it installed itself in the wrong place. Fixed.

**Comment by jhjin** [comment]
https://github.com/e-lab/torch-toolbox/commit/296b2ec90cfe3cc4c2b5445cce1cf844cb632eea fixes #7
