### ISSUE TITLE
libvideo_decoder.so: undefined symbol: av_frame_unref

### ISSUE THREAD

**Issue by InnovArul** [e-lab/torch-toolbox#8]
I am getting the following error when I try to load video using video_decoder.

-> % qlua test-frame.lua -v 1DCnIad1Y0w.mp4 
Unable to connect X11 server (continuing with -nographics)
qlua: error loading module 'libvideo_decoder' from file './libvideo_decoder.so':
	./libvideo_decoder.so: undefined symbol: av_frame_unref
stack traceback:
	[C]: at 0x7fc4456649c0
	[C]: at 0x7fc445439bd0
	[C]: in function 'require'

What could be the issue? could you please help?

**Comment by mvitez** [comment]
If you are getting this error, it means that you are making it with make NEWFFMPEG=1.
Try making it without NEWFFMPEG=1.
